apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: fashionograf-authentication-deployment
spec:
  replicas: 1
  template:
    metadata:
      name: fashionograf-authentication
      labels:
        app: fashionograf-authentication
    spec:
      containers:
        - image: kriola/fashionograf-authentication:8a9f932
          name: fashionograf-authentication-container
          envFrom:
            - configMapRef:
                name: authentication-config
          ports:
            - containerPort: 3000
