apiVersion: v1
kind: ConfigMap
metadata:
  name: authentication-config
data:
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: admin
  POSTGRES_DB: db
  POSTGRES_URL: authentication-postgres-service
  NODE_ENV: production
  PORT: "3000"
