apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: authentication
spec:
  replicas: 1
  template:
    metadata:
      name: authentication
      labels:
        app: authentication
    spec:
      containers:
        - image: kriola/fashionograf-authentication:e691e02
          name: authentication-container
          envFrom:
            - configMapRef:
                name: authentication
            - secretRef:
                name: authentication
          ports:
            - containerPort: 3000
              name: authentication
