apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: authentication-mongo-deployment
spec:
  template:
    metadata:
      labels:
        app: authentication-mongo
    spec:
      containers:
        - image: "mongo:4.0.3"
          name: mongo
          envFrom:
            - configMapRef:
                name: authentication-mongo
            - secretRef:
                name: authentication-mongo
          ports:
            - containerPort: 27017
              name: mongo
          volumeMounts:
            - name: authentication-storage
              mountPath: /data/db
      volumes:
        - name: authentication-storage
          persistentVolumeClaim:
            claimName: authentication-pvc
