apiVersion: v1
kind: Service
metadata:
  name: authentication-mongo
spec:
  type: NodePort
  ports:
    - port: 27017
      targetPort: mongo
      protocol: TCP
  selector:
    app: authentication-mongo
